### ISSUE TITLE
`APIException: image has incompatible architecture` using `runs-on: [self-hosted, type-cax11]`

### ISSUE THREAD

**Issue by NiklasRosenstein** [testflows/TestFlows-GitHub-Hetzner-Runners#10]
Hi, thanks a lot for this project!

I've created an instance of the controller using `github-hetzner-runners cloud deploy` using the latest version (`1.5.231020.1122452`) without any configuration beyond the credentials. A job with `runs-on: [self-hosted, type-cax11]` hangs and in the logs I can find

```
Dec 15 16:11:40 github-hetzner-runners github-hetzner-runners[2873]: 16:11:40 ❌ APIException: image has incompatible architecture
```

I can fix this by adding the `image-arm-system-ubuntu-22.04` label, but it would be nice if I didn't have to. The README of this project also shows an example using an Ampere server without this label.

**Comment by vzakaznikov** [comment]
Hi @NiklasRosenstein, thanks for the issue! Yes, this can be fixed. It is a special case. Right now the code tries to be as generic as possible without really understanding what `type-cax11` actually means. But for this simple case, I do agree that it should do the right thing and pick a correct default image.

**Comment by vzakaznikov** [comment]
@NiklasRosenstein, I've reviewed the code, and I don't think creating a special case is a good idea.
For now, I've updated the docs (https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners?tab=readme-ov-file#arm64-runners) to highlight that if type is changed to ARM machine, it means that the image should also be set appropriately. There are too many corner cases if we try to interpret user options, which could bring more issues than the convenience is worth.

**Comment by vzakaznikov** [comment]
Closing this issue. The fix was an improvement to the docs.

**Comment by NiklasRosenstein** [comment]
Ah, that's unfortunate. I've set up our runner to use the `app-docker-ce` image by default now, so the x86 jobs don't need the `image-` label, but we still need to set it on the arm jobs. Thanks for looking into it!

**Comment by vzakaznikov** [comment]
Starting with the https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/releases/tag/1.6.240228.1182937 release you can use meta labels as a workaround. Please see https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/wiki/Meta-Labels.

For example, you can make the `type-cax11` a meta label that will combine both the custom server type and the custom image
labels.

```bash
github-hetzner-runners --meta-labels type-cax11 "type-cax11,image-arm-system-ubuntu-22.04"
```

then

```yaml
runs-on: [self-hosted, type-cax11]
```

will pick the right image.

By default, the server type is still x86 and the default image is `image-x86-system-ubuntu-22.04`.
