### ISSUE TITLE
Run for multiple repositories or an entire organization

### ISSUE THREAD

**Issue by NiklasRosenstein** [testflows/TestFlows-GitHub-Hetzner-Runners#12]
Is it possible to run in multiple repositories or an entire organization?

I've try to start the github-actions-runner process multiple times, once per GitHub repository but they seem to be stepping on each other's toes when they're in the same HCloud project (this is conjecture).

**Comment by NiklasRosenstein** [comment]
Maybe it's not an issue with them living in the same project after all. I'm not sure why I'm getting this error when the runner tries to register:

```
00:03:09    >
00:03:09    > Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: D4E6:8FE99:6A3AFB2:6B6EFFF:659F303D)
00:03:09    > {"message":"Unable to find runner owner.","documentation_url":"https://docs.github.com/rest"}
```

**Comment by NiklasRosenstein** [comment]
This https://github.com/None seems fishy though!


```
00:04:52    > + ./config.sh --unattended --replace --url https://github.com/None --token REDACTED --name github-hetzner-runner-7482176451-20365423938 --runnergroup Default --labels self-hosted,type-cpx21 --work _work --ephemeral
```

**Comment by NiklasRosenstein** [comment]
Found it, I was using `--github-repository=org/repo` instead of the `GITHUB_REPOSITORY` environment variable. Seems like the CLI option doesn't propagate correctly.

**Comment by NiklasRosenstein** [comment]
The original question still stands though. I've just experienced the Testflows controller for repo A powering off a VM created by controller for repo B because it considered it a zombie. 😄

**Comment by vzakaznikov** [comment]
Hi @NiklasRosenstein! Yes, currently you need to create a unique Hetzner project per repository. This is a known limitation for now as mentioned in the docs https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners?tab=readme-ov-file#limitations.

**Comment by vzakaznikov** [comment]
> Found it, I was using --github-repository=org/repo instead of the GITHUB_REPOSITORY environment variable. Seems like the CLI option doesn't propagate correctly.

I'll need to double check the code. The command line option should be respected. Can you reproduce the issue? If you are using a cloud service then the option will be set during service deployment. After that you can't change it.

**Comment by vzakaznikov** [comment]
@NiklasRosenstein, if you can reproduce the issue with the --github-repository CLI option please create another issue.
I will close this one as using the same Hetzner project for multiple repositories or providing runners for an entire organization
is not supported right now as stated in the docs. Feel free to open a feature request for future development.

**Comment by NiklasRosenstein** [comment]
#13 !
