### ISSUE TITLE
`--github-repository` option does not propagate into setup script

### ISSUE THREAD

**Issue by NiklasRosenstein** [testflows/TestFlows-GitHub-Hetzner-Runners#13]
When using `github-hetzner-runners --github-repository acme/repo` instead of `GITHUB_REPOSITORY=acme/repo github-hetzner-runners`, it seems the GitHub Actions runner created by the controller to run with `GITHUB_REPOSITORY=None`, causing the default setup script to run `./config.sh --url https://github.com/None ...`.

**Comment by vzakaznikov** [comment]
Thanks @NiklasRosenstein! I will take a look.

**Comment by vzakaznikov** [comment]
Should be fixed in https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/releases/tag/1.5.240116.1161741.

**Comment by NiklasRosenstein** [comment]
Thanks!
