### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by guidoiaquinti** [testflows/TestFlows-GitHub-Hetzner-Runners#19]
👋 Hi! First of all, nice project! I've tried to deploy the service using [your documentation](https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/wiki/Running-as-a-Cloud-Service). I can see the VM provisioned correctly but it's failing to register as GitHub self-hosted runner. Here's the log from `github-hetzner-runners cloud status`:
 
```
14:39:19    > May 24 12:37:53 github-hetzner-runners github-hetzner-runners[3647]: 12:37:53 🍀 Found new potential zombie server github-hetzner-runner-9224036990-25378510349
14:39:19    > May 24 12:38:00 github-hetzner-runners github-hetzner-runners[3647]: 12:38:00 🍀 Trying to connect to github-hetzner-runner-9224036990-25378510349@XXXXX...1
14:39:19    > May 24 12:38:08 github-hetzner-runners github-hetzner-runners[3647]: 12:38:08 🍀 Trying to connect to github-hetzner-runner-9224036990-25378510349@XXXXX...2
14:39:19    > May 24 12:38:13 github-hetzner-runners github-hetzner-runners[3647]: 12:38:13 🍀 Trying to connect to github-hetzner-runner-9224036990-25378510349@XXXXX...3
14:39:19    > May 24 12:38:15 github-hetzner-runners github-hetzner-runners[3647]: 12:38:15    > github-hetzner-runner-9224036990-25378510349
14:39:19    > May 24 12:38:15 github-hetzner-runners github-hetzner-runners[3647]: 12:38:15 🍀 Getting registration token for the runner
14:39:19    > May 24 12:38:15 github-hetzner-runners github-hetzner-runners[3647]: 12:38:15 ❌ TypeError: cannot unpack non-iterable NoneType object
14:39:19    > May 24 12:38:35 github-hetzner-runners github-hetzner-runners[3647]: 12:38:35 🍀 Logging in to GitHub
14:39:19    > May 24 12:38:35 github-hetzner-runners github-hetzner-runners[3647]: 12:38:35 🍀 Checking current API calls consumption rate
14:39:19    > May 24 12:38:36 github-hetzner-runners github-hetzner-runners[3647]: 12:38:36 🍀 Consumed 4 calls in 60 sec, 4965 calls left, reset in 3317 sec
```

Version
```
(infrastructure) ➜  infrastructure git:(main) ✗ github-hetzner-runners -v
1.7.240516.1143322
```

**Comment by vzakaznikov** [comment]
Hi @guidoiaquinti, could you double check the permissions of your GitHub token and repository URL?
Here is the code where it is failing for you https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/blob/main/testflows/github/hetzner/runners/scale_up.py#L118.

**Comment by vzakaznikov** [comment]
Please make sure you set all three environment variables to the values that correspond to your project.
Specifically, the GITHUB_REPOSITORY should specify your project's repository for which you have created a GITHUB_TOKEN
that has the correct permissions. See https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners?tab=readme-ov-file#getting-started-tutorial for more details.

For example,

```
export GITHUB_TOKEN=ghp_...
export GITHUB_REPOSITORY=...
export HETZNER_TOKEN=GJzdc...

github-hetzner-runners cloud deploy
```

**Comment by vzakaznikov** [comment]
I've doubled checked against my https://github.com/vzakaznikov/demo-testflows-github-hetzner-runners/ repository by deploying new cloud service and everything works as expected.

Please let me know if you still can't get it to work. You could dump full logs by running `github-hetzner-runners cloud log` command. Also, don't forget to delete any servers after any trial runs using `github-hetzner-runners delete` and `github-hetzner-runners cloud delete` commands.

**Comment by guidoiaquinti** [comment]
👋 Hi everyone! Thank you for your help. I discovered that the issue was indeed related to the type of token used: I initially created a "Fine-grained token" instead of a "Token (classic)," which caused the problem.

**Comment by vzakaznikov** [comment]
The fine-grained tokens could work, but I haven't tried using them yet to see what specific permissions they need.

**Comment by vzakaznikov** [comment]
I've tried different combinations of permissions for the fine-grained tokens but none work. So yes, fine-graned tokens can't be used.

**Comment by guidoiaquinti** [comment]
> I've tried different combinations of permissions for the fine-grained tokens but none work. So yes, fine-graned tokens can't be used.

Thank you for double checking! 🙏
