### ISSUE TITLE
Support custom prefixes for labels.

### ISSUE THREAD

**Issue by MyroTk** [testflows/TestFlows-GitHub-Hetzner-Runners#2]
Instead of `type-...`, labels should have the option to include a prefix to the label, e.g. `prefix-type-...` .

**Comment by vzakaznikov** [comment]
Added support for `--label-prefix`.

```
 --label-prefix prefix
                        support type, image, and location job labels with the specified prefix
```
It only applies to `type-...`, `in-...` and `image-...` labels.
