### ISSUE TITLE
Disable custom scripts for apps and snapshots.

### ISSUE THREAD

**Issue by MyroTk** [testflows/TestFlows-GitHub-Hetzner-Runners#3]
A flag to disable running custom setup/startup scripts when using an app or a snapshot.

Because Heztner snapshots can take a while to load (5+ min), it is more convenient to run the setup script. But this interferes with existing apps. For example, I have a setup script that adds docker, but when using the Hetzner docker app, it causes issues on launch.

**Comment by vzakaznikov** [comment]
Ok, we could add this. How would it work?

Maybe add via a labels?

Something like:

`image-x86-app-docker-ce[-no-setup[-no-startup]]`?

**Comment by vzakaznikov** [comment]
Will be supported by https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/tree/job-specific-scripts using an empty script and runner labels `[startup-none, setup-none]` where `none` will refer to an empty script inside the `--scripts` folder.
We should probably provide an empty `none.sh` inside the `/scripts` folder by default.

**Comment by vzakaznikov** [comment]
Can be done in 1.6 using the `startup-none` and `setup-none` labels.
