### ISSUE TITLE
Upgrade to latest hcloud package

### ISSUE THREAD

**Issue by jooola** [testflows/TestFlows-GitHub-Hetzner-Runners#40]
The latest package include type definition, which should help you develop your tool.

It also includes a bunch of fixes that a probably worth having.

https://github.com/hetznercloud/hcloud-python/blob/main/CHANGELOG.md

**Comment by vzakaznikov** [comment]
Hi @jooola, thanks for this and other issues. We will work on implementing them. For this specific case, moving to the latest hcloud package should be easy.
