### ISSUE TITLE
Server creation fails due to deprecated server type

### ISSUE THREAD

**Issue by saiqulhaq** [testflows/TestFlows-GitHub-Hetzner-Runners#45]
Hello,

I encountered an issue with the GitHub Hetzner Runners. The runners stopped working due to a deprecated server type. Specifically, Hetzner has deprecated the `cx11` server type, causing the runner creation to fail.

I had to modify the server creation code to override the deprecated server type to resolve this. Here's the change I made:

```python
# Old code
with Action(f"Creating server {name} with labels {labels}", server_name=name):
    response = client.servers.create(
        name=name,
        server_type=server_type,
        location=server_location,
        image=server_image,
        ssh_keys=ssh_keys,
        labels=server_labels,
    )
    server: BoundServer = response.server

# New code
with Action(f"Creating server {name} with labels {labels}", server_name=name):
    # cx11 has been deprecated
    # we need to override to use cx22 instead
    if server_type.name == "cx11":
        server_type = ServerType(name="cx22")

    response = client.servers.create(
        name=name,
        server_type=server_type,
        location=server_location,
        image=server_image,
        ssh_keys=ssh_keys,
        labels=server_labels,
    )
    server: BoundServer = response.server
```
testflows/github/hetzner/runners/scale_up.py

I have tried to find any cx-11 code in my repo, but I couldn't find it. So I am not sure if this issue is actually because of my repo or because of the wrong config

**Comment by vzakaznikov** [comment]
Hi @saiqulhaq, `cx11` has been removed as the default server type. Could you please try the latest version?
