### ISSUE TITLE
Recurring error during server recycling process

### ISSUE THREAD

**Issue by saiqulhaq-hh** [testflows/TestFlows-GitHub-Hetzner-Runners#46]
Hello,

I've encountered a recurring issue with the GitHub Hetzner Runners, specifically during the server recycling process. The error occurs when attempting to rebuild a recycled server's image. Here's the error log:

```
🍀 Validating server github-hetzner-runner-standby-1735285900197709 labels
12/27/2024 07:51:40 AM INFO     recycle_server  🍀 Get recyclable server github-hetzner-runner-recycle-17352858904909
12/27/2024 07:51:40 AM INFO     recycle_server  🍀 Recycling server github-hetzner-runner-recycle-17352858904909 to make github-
                                                hetzner-runner-standby-1735285900197709
12/27/2024 07:51:41 AM INFO     recycle_server  🍀 Rebuilding recycled server github-hetzner-runner-standby-1735285900197709
                                                image
12/27/2024 07:51:41 AM ERROR    __exit__        ❌ AttributeError: 'RebuildResponse' object has no attribute
                                                'wait_until_finished'
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/github-hetzner-runners", line 1281, in <module>
    arguments.func(args=arguments, config=config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/testflows/github/hetzner/runners/service.py", line 240, in format_log
    wrapped = [
  File "/home/ubuntu/.local/lib/python3.10/site-packages/testflows/github/hetzner/runners/service.py", line 241, in <listcomp>
    (width, Wrapper(width).wrap(columns[index])) for _, index, width in selected
IndexError: list index out of range
```

I've been able to temporarily resolve this issue by deleting and recreating the runner, but I've had to do this almost daily. This workaround is not sustainable and indicates an underlying problem that needs addressing.

I'm happy to provide any additional information or logs that might help diagnose and resolve this issue. Please let me know if you need any further details.

Thank you for your attention to this matter.

**Comment by vzakaznikov** [comment]
This is a bug introduced by moving to the latest version of hcloud. In https://github.com/hetznercloud/hcloud-python/blob/main/hcloud/actions/client.py#L14 BoundAction has wait_until_finished and now is accessed using the action attribute of the RebuildResponse https://github.com/hetznercloud/hcloud-python/blob/b2fae541592ddf74ae9ecc54f34d75b6bfecf19a/hcloud/servers/domain.py#L266.

**Comment by vzakaznikov** [comment]
Should be fixed in https://pypi.org/project/testflows.github.hetzner.runners/1.7.241227.1160242/.
