### ISSUE TITLE
Removing recycle server instances that use dedicated vCPU

### ISSUE THREAD

**Issue by MyroTk** [testflows/TestFlows-GitHub-Hetzner-Runners#5]
Recycled servers count against the Heztner D.vCPU limit and prevent new servers from being created.

For example, if the the D.vCPU limit is 32 and a job that uses ccx53 follows a job that uses ccx43, the ccx43 instance is going to sit in a powered off state waiting to be recycling, preventing the ccx53 from being created.

**Comment by vzakaznikov** [comment]
Yes, this is a problem. Right now the workaround is just to use the same dedicated server types or turn off server recycling.

Not sure how to exactly fix it. Need to look into this. Right now we don't have a logic to check which server uses which resources. Maybe we could start killing random recyclable servers if we see an API exception that implies that we've hit some limit.

**Comment by vzakaznikov** [comment]
Should be partially covered by the https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/releases/tag/1.5.231010.1002212.

However, right now we don't check if any of the recyclable server have ccx type. That's something that still needs to be added.
We will just either remove a recyclable server at random or the cheapest one.

**Comment by vzakaznikov** [comment]
No planned for now.
